# Generated by Django 4.2.1 on 2023-06-26 23:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="createfriend",
            old_name="usersFriend",
            new_name="userFriend",
        ),
    ]
