# Generated by Django 4.2.1 on 2023-06-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0002_rename_usersfriend_createfriend_userfriend"),
    ]

    operations = [
        migrations.AddField(
            model_name="createfriend",
            name="is_replay",
            field=models.BooleanField(default=False),
        ),
    ]
