# Generated by Django 4.2.1 on 2023-06-27 15:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("friends", "0003_createfriend_is_replay"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="createfriend",
            unique_together={("user", "userFriend")},
        ),
    ]
