# Generated by Django 4.2.1 on 2023-06-27 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0004_alter_createfriend_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="createfriend",
            name="is_replay",
        ),
    ]
