# Generated by Django 4.2.1 on 2023-06-23 18:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("postsUsers", "0008_alter_post_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("commentPost", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CommandPost",
            new_name="CommentPost",
        ),
    ]
