# Generated by Django 4.2.1 on 2023-06-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postsUsers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="photoPosts/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="postPosts/%Y/%m/%d/"
            ),
        ),
    ]
