# Generated by Django 4.2.1 on 2023-06-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postsUsers", "0002_alter_post_photo_alter_post_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="videoPosts/%Y/%m/%d/"
            ),
        ),
    ]
