# Generated by Django 4.2.1 on 2023-06-07 22:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logAndReg", "0006_alter_user_profile_picture"),
        ("postsUsers", "0003_alter_post_video"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Post",
            new_name="Posts",
        ),
        migrations.AlterModelTable(
            name="posts",
            table="posts",
        ),
    ]
