# Generated by Django 4.2.1 on 2023-06-07 22:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logAndReg", "0006_alter_user_profile_picture"),
        ("postsUsers", "0004_rename_post_posts_alter_posts_table"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Posts",
            new_name="Post",
        ),
        migrations.AlterModelTable(
            name="post",
            table="post",
        ),
    ]
